name: Docker Image CI

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=platform::linux/${{ matrix.architecture }}
          echo ::set-output name=tag::${GITHUB_REPOSITORY}:${{ matrix.architecture }}-${GITHUB_SHA:0:7}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ steps.prep.outputs.platform }}
          push: true
          tags: ${{ steps.prep.outputs.tag }}
